version: '2'
services:
    atividade03-app:
        image: atividade03
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://atividade03-mysql:3306/atividade03?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    atividade03-mysql:
        extends:
            file: mysql.yml
            service: atividade03-mysql
